"""Tool implementations executed by the orchestrator.

Every tool result is either SQL-derived data (numbers) or pgvector-retrieved
evidence (explanations). Nothing here is generated by a model.

The evidence tool also attaches a private ``_trace`` payload (query embedding,
ranking scores, provenance) which the orchestrator consumes for the RAG trace
and strips before the result is sent to the LLM.
"""
from __future__ import annotations

import json

from app.retrieval.service import retrieve
from app.retrieval.sql import deterministic_calculation, structured_price_query
from app.retrieval.temporal import TimePeriod, parse_time_period

# Fields safe to expose to the LLM (no URLs → the model cannot invent citations;
# no embeddings → don't bloat context).
_LLM_CHUNK_FIELDS = (
    "id",
    "document_title",
    "section",
    "source_name",
    "source_type",
    "published_date",
    "start_year",
    "end_year",
    "semantic_similarity",
    "temporal_score",
    "authority_score",
    "final_score",
    "text",
)


def _period_from_arg(arg: str | None) -> TimePeriod:
    if arg:
        return parse_time_period(arg)
    return TimePeriod()


def _period_dict(period: TimePeriod) -> dict:
    return {
        "start": period.start.isoformat() if period.start else None,
        "end": period.end.isoformat() if period.end else None,
    }


def _shape_for_llm(chunks: list[dict]) -> list[dict]:
    return [{k: c.get(k) for k in _LLM_CHUNK_FIELDS} for c in chunks]


def tool_structured_price_lookup(args: dict) -> dict:
    series_id = args.get("series_id") or None
    period = _period_from_arg(args.get("period"))
    return structured_price_query(question="", period=period, series_id=series_id)


def tool_deterministic_calculation(args: dict) -> dict:
    period = _period_from_arg(args.get("period"))
    return deterministic_calculation(
        operation=args["operation"],
        period=period,
        series_id=args.get("series_id") or None,
    )


def tool_evidence_search(args: dict) -> dict:
    query = args["query"]
    period = _period_from_arg(args.get("period"))
    result = retrieve(query, period)

    public = {
        "retrieval_query": result.retrieval_query,
        "requested_period": _period_dict(result.period),
        "candidate_count": result.candidate_count,
        "chunks": _shape_for_llm(result.ranked),
    }
    trace = {
        "retrieval_query": result.retrieval_query,
        "requested_period": _period_dict(result.period),
        "query_embedding": result.query_embedding,
        "embedding_dim": len(result.query_embedding),
        "candidate_count": result.candidate_count,
        "top_n": result.top_n,
        "weights": result.weights,
        "formula": result.formula,
        "chunks": result.ranked_all,  # full ranked list (top_n passed to LLM)
    }
    public["_trace"] = trace
    return public


TOOL_DISPATCH = {
    "structured_price_lookup": tool_structured_price_lookup,
    "deterministic_calculation": tool_deterministic_calculation,
    "evidence_search": tool_evidence_search,
}


def execute_tool(name: str, arguments: str) -> dict:
    args = json.loads(arguments or "{}")
    fn = TOOL_DISPATCH.get(name)
    if fn is None:
        return {"error": f"unknown tool: {name}"}
    try:
        return fn(args)
    except Exception as exc:  # surface tool errors to the agent
        return {"error": str(exc)}
